# Generated by Django 5.2 on 2025-04-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat_facts',
            new_name='cat_fact',
        ),
    ]
