# Generated by Django 5.2 on 2025-04-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_rename_cat_facts_cat_fact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cat_fact',
            new_name='Fact',
        ),
    ]
