# Generated by Django 5.2 on 2025-04-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_rename_cat_fact_fact'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='breed',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
